[package]
name = "matx_dev"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "matx_dev"
path = "src/lib.rs"

[dependencies]
comrak = "0.39.0"
fs_extra = "1.3.0"
minijinja = "2.10.2"

[workspace]
members = ["serve"]
