[package]
name = "matx_dev"
version = "0.1.0"
edition = "2024"

[dependencies]
comrak = "0.39.0"
fs_extra = "1.3.0"
minijinja = "2.10.2"
serde = { version = "1.0.219", features = ["derive"] }
yaml-rust2 = "0.10.1"

[workspace]
members = ["serve"]
